# General setup to build and run tests on the project whenever committing
sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

  - docker build -t jhasangjekaj/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jhasangjekaj/react-test npm test -- --coverage

after_success:
    - docker build -t jhasangjekaj/multi-client ./client
    - docker build -t jhasangjekaj/multi-nginx ./nginx
    - docker build -t jhasangjekaj/multi-server ./server
    - docker build -t jhasangjekaj/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to the docker hub
    - docker push jhasangjekaj/multi-client
    - docker push jhasangjekaj/multi-nginx
    - docker push jhasangjekaj/multi-server
    - docker push jhasangjekaj/multi-worker

# Deploy to production only when thera are changes to master branch
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-269924676398"
  bucket_path: "multi-docker"
  on:
    branch: master-not-now
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
