apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      compponent: worker
  template:
    metadata:
      labels:
        compponent: worker
    spec:
      containers:
        - name: worker
          image: jhasangjekaj/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"